openapi: '3.0.3'
info:
  title: world-downloads
  version: '1.0.0'
servers:
  - url: http://api-minecraft.nearzero.io/
    description: Production server
  - url: http://api-minecraft.nearzero.io/
    description: Beta server
paths: {}